### ISSUE TITLE
Forge 1.21 supported?

### ISSUE THREAD

**Issue by Tursiops-G** [mestiez/ImmortalPets#1]
CF/Modrinth Listing shows Forge 1.20.1 thru 1.21 is supported, but the mod needs Architectury installed (which ISN'T available for Forge 1.21) in order to load.

**Comment by mestiez** [comment]
Aw, the version list is inaccurate (it is automatic). The mod doesn't use the Architectury API anyway, so technically the only thing that you'd have to do is copy the mixin and make a raw Forge mod with it.
